on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "* 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  fetch:
    name: fetch
    runs-on: ubuntu-latest
    steps:
      # Checkout current branch / repo
      - uses: actions/checkout@v2

      # Generates the feeds.json
      - name: Fetch RSS feeds as JSON
        uses: i-valchev/rss-to-json@0.0.3
        with:
          source: /home/runner/work/productnews/productnews/feeds.yaml # temporary
          target: /home/runner/work/productnews/productnews/feeds.json # temporary

      # Commit chnages to repo
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: Update feeds.json with RSS data.
